name: Bump and Publish

on:
  release:
    types: [released]
    # refs/tags/x.x.x
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
   tests:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v3
         with:
           node-version: '18'
           cache: 'yarn'
       - run: yarn
       - run: yarn test
   bump-and-build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npm --no-git-tag-version --allow-same-version version ${{ steps.get_version.outputs.VERSION }}
      - run: npm run build
      - run: npm pack
      - name: 'Upload Build Artifatc ${{ steps.get_version.outputs.VERSION }}'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_version.outputs.VERSION }}.tgz
          path: piwikpro-gatsby-plugin-piwik-pro-${{ steps.get_version.outputs.VERSION }}.tgz
   publish-npm:
      needs: bump-and-build
      runs-on: ubuntu-latest
      steps:
          - name: Get the version
            id: get_version
            run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          - name: Download a Build Artifact
            uses: actions/download-artifact@v2
            with:
              name: ${{ steps.get_version.outputs.VERSION }}.tgz
          - uses: actions/setup-node@v3
            with:
              node-version: '18'
              cache: 'yarn'
              registry-url: https://registry.npmjs.org/
          - run: npm publish piwikpro-gatsby-plugin-piwik-pro-${{ steps.get_version.outputs.VERSION }}.tgz
            env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
