name: Build and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-checks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './plugin'
    steps:
      # Build plugin
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./plugin/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install Modules
        run: npm ci

      - name: Build
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm run test

      # Build example app
      - name: Install modules
        run: npm ci
        working-directory: ./example

      - name: Build
        run: npm run build
        working-directory: ./example

      # Check documentation
      - name: Generate documentation
        run: npm run build:docs

      - name: Check for documentation changes
        run: |
          if [[ -n $(git status --porcelain | grep "README.md") ]]; then
            echo "Documentation is not up to date!"
            exit 1
          fi

  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ./plugin/package-lock.json
            ./example/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install plugin modules
        run: npm ci
        working-directory: ./plugin

      - name: Build plugin
        run: npm run build
        working-directory: ./plugin

      - name: Install example modules
        run: npm ci
        working-directory: ./example

      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium
        working-directory: ./example

      - name: Run e2e tests
        run: npm run test:e2e
        working-directory: ./example
