name: Build and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-checks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './plugin'
    steps:
      # Build plugin
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: ./plugin/yarn.lock
          registry-url: 'https://registry.npmjs.org'

      - name: Install Modules
        run: yarn

      # Run tests
      - name: Run tests
        run: yarn test

      # Build example app
      - name: Install modules
        run: yarn install --frozen-lockfile
        working-directory: ./example

      - name: Build
        run: yarn build
        working-directory: ./example
